# CircleCI 2.0 configuration file for Go.
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - run: golangci-lint run
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - codecov/upload:
          file: coverage.txt
      
